//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.23 at 10:25:15 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:inftec.ch/ju/util/xml/ns/ref", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.inftec.ju.util.xml.ns.ref;
